config/routes.rb
Linkity::Application.routes.draw do
  devise_for :users

  resources :users
  resources :comments

  resources :posts do
    resource :vote
    resources :comments
  end
  
  root :to => "posts#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  has_many :comments
  belongs_to :post
  belongs_to :user
  
  validates_presence_of :comment
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  has_many :comments, :dependent => :destroy
  has_many :votes, :as => :voted, :dependent => :destroy
  belongs_to :user
  
  validates_presence_of :url
  validates_presence_of :user
  validates_format_of :url, :with => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix
  
  def self.top(opts = {:limit => 100})
    self.all(:limit => opts[:limit]).sort{|a,b|
      b.score <=> a.score
    }
  end
  
  before_save :discover_name!
  
  def discover_name! # should find the title of the page
    unless self.name? then
      a = Mechanize.new { |agent|
        agent.open_timeout = 1.second
      }

      a.get(self.url) do |page|
        p page
        self.name = page.title
      end
    end
  end
  
  def display_score
    self.votes.sum(:value)
  end
  
  def age_in_minutes
    (Time.current.to_i - self.created_at.to_i).to_f / 1.minute.to_f
  end
  
  def score
    self.votes.sum(:value).to_f + (self.age_in_minutes * $minute_vote_weight)
  end
  
end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :posts
  has_many :comments
  has_many :votes

#  has_many :commented

  def to_s
    email
  end

  def gravatar(size = 32)
    email_address = self.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    image_src = "http://www.gravatar.com/avatar/#{hash}?s=#{size}"
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voted, :polymorphic => true
  belongs_to :user
  
  validates_uniqueness_of :voted_id, :scope => [:user_id, :voted_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
    
  def create
    @comment = Comment.new(params[:comment])
    @comment.user = current_user
    @comment.post = Post.find(params[:post_id]) if params[:post_id]
    
    if @comment.save then
      flash[:notice] = I18n.t('comment.created')
      redirect_to :back
    else
      redirect_to :back
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index,:newest]
  
  def index
    @posts = Post.top
  end
  
  def newest
    render :index
  end
  
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new(:post => @post)
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(params[:post])
    @post.user = current_user
    
    if @post.save then
      flash[:notice] = I18n.t('post.created')
      redirect_to '/'
    else
      render :new
    end
  end
  
  def destroy
    
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!
  
  def create
    @vote = Vote.new({
      :voted => Post.find(params[:post_id]),
      :user => current_user
    })
    
    if @vote.save then
      respond_to do |format|
        format.html{
          flash[:notice] = I18n.t('vote.created')
          redirect_to posts_path
        }
        format.js {}
      end
    else
      respond_to do |format|
        format.html {
          flash[:notice] = I18n.t('vote.not_created')
          redirect_to posts_path
        }
        format.js {}
      end
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="comment" id="<%=dom_id(comment)%>">
<strong><%=comment.user.to_s%></strong> says: <%=comment.comment%>

<%= render :partial => '/comments/comment', :collection => comment.comments # HOLY SHIT RECURSION SON BOOM 
%>
</div>

app/views/comments/_form.html.erb
<%=semantic_form_for [@post,@comment] do |f| %>
	
	<%= f.inputs do %>
    	
		<%=f.input :comment %>

	<% end %>

    <% f.buttons do %>
      <%= f.commit_button %>
    <% end %>
	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=I18n.t('site.name')%></title>
  <%= stylesheet_link_tag 'application','formtastic','reset' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="header">
	<h1><%=link_to I18n.t('site.name'), posts_path %></h1>
	
	<ol id="nav">
		<li><%=link_to I18n.t('nav.new_post'), new_post_path %></li>
	</ol>
	
	<div id="user">
		<% if current_user then %>
			<%=link_to current_user.to_s, edit_user_registration_path %> &mdash; <%=link_to 'Log Out', destroy_user_session_path %>
		<% else %>
			<%=link_to 'Log In', new_user_session_path %> | <%=link_to 'Register', new_user_registration_path %>
		<% end %>
	</div>
</div>

<div id="flashes">
	<%=flash[:notice]%>
	<%=flash[:error]%>
	<%=flash[:info]%>
</div>

<div id="content">
<%= yield %>
</div>

<div id="footer">
	<%=I18n.t('site.name')%> is powered by <%=link_to 'linkity', 'http://github.com/adrianpike/linkity' %>. [ <%=link_to 'Report a bug', 'https://github.com/adrianpike/linkity/issues' %> | <%=link_to 'Learn more', 'https://github.com/adrianpike/linkity/wiki' %> ]
</div>

</body>
</html>

app/views/posts/_post.html.erb
<div class="post" id="<%=dom_id(post)%>">
	<%=link_to 'Vote Up', post_vote_path(post), :method => 'post', :class => 'upvote' %>
	<span class="score"><%=post.display_score%> votes</span>
	
	<strong class="title"><%=link_to (post.name? ? post.name : post.url), post.url %></strong>
	<span class="url">(<%=post.url%>)</span>
	
	<em class='submission-info'>Submitted by <%=link_to post.user.to_s, user_path(post.user)%> about <%=time_ago_in_words(post.created_at)%> ago</em>
	<span class="comments"><%=link_to post.comments.count.to_s+' comments', post_path(post)%></span>
</div>

app/views/posts/index.html.erb
<%=render :partial => '/posts/post', :collection => @posts %>

app/views/posts/new.html.erb
<%=semantic_form_for @post do |f| %>
	
	<%= f.inputs do %>
    	
		<%=f.input :url %>
		<%=f.input :name %>

	<% end %>

    <% f.buttons do %>
      <%= f.commit_button %>
    <% end %>

<% end %>

app/views/posts/show.html.erb
<h2><%=link_to @post.name, @post.url%></h2>
<h3><%=@post.url%></h3>

<div id="description"><%=@post.description%></div>

<%=render :partial => '/comments/comment', :collection => @post.comments %>
<%=render :partial => '/comments/form' %>

app/views/users/show.html.erb
<h1><%= @user %></h1>
<%= image_tag @user.gravatar(64) %>